/**
 * Created by yura on 16.12.16.
 */

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT";
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT";

export const ENTER_PROMO = "ENTER_DISCOUNT";
export const REMOVE_PROMO = "REMOVE_PROMO";

export const START_FETCHING_PRODUCTS = "START_FETCHING_PRODUCTS";
export const FINISH_FETCHING_PRODUCTS = "FINISH_FETCHING_PRODUCTS";

export const START_FETCHING_PROMOCODE = "START_FETCHING_PROMOCODE";
export const FINISH_FETCHING_PROMOCODE = "FINISH_FETCHING_PROMOCODE";